apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.misc.app_name }}-deployment
spec:
  replicas: {{ .Values.misc.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.misc.app_name }}
  template:
    metadata:
      name: {{ .Values.misc.app_name }}
      labels:
        app: {{ .Values.misc.app_name }}
    spec:
      containers:
      - image: {{ .Values.misc.app_image }} 
        name: main
