apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.misc.app_name }}-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: {{ .Values.netconf.app_port }}
    nodePort: {{ .Values.netconf.node_port }}
  selector:
    app: {{ .Values.misc.app_name }}
