apiVersion: v1
kind: Service
metadata:
  name: java-web-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: {{ .Values.netconf.app_port }}
    nodePort: {{ .Values.netconf.node_port }}
  selector:
    app: java-web
